version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - restore_cache:
          keys:
          - deps-{{ checksum "bower.json" }}-{{ checksum "examples/bower.json" }}

      - run:
          command: |
            git checkout -b gh-pages
            git reset --hard origin/master

      - run:
          working_directory: examples
          command: |
            yarn add --dev bower purescript pulp
            yarn
            yarn build:ps

      - save_cache:
          paths:
            - bower_components
            - output
            - examples/node_modules
            - examples/bower_components
          key: deps-{{ checksum "bower.json" }}-{{ checksum "examples/bower.json" }}

      - run:
          working_directory: examples
          command: |
            yarn build

      - run:
          command: |
            cp docs/* .
            git config user.email "remotenonsense@gmail.com"
            git config user.name "CircleCI"
            git add . && git commit -am 'build gh-pages'
            # https://stackoverflow.com/a/48763205
            git push -q -f https://${GH_PAGES_TOKEN}@github.com/rnons/purescript-halogen-storybook.git gh-pages

workflows:
  version: 2
  build-gh-pages:
    jobs:
      - build:
          context: gh-pages
          filters:
            branches:
              only:
                - master
